namespace MoonSharp.Interpreter.Interop;

public enum ReflectionSpecialNameType
{
	IndexGetter,
	IndexSetter,
	ImplicitCast,
	ExplicitCast,
	OperatorTrue,
	OperatorFalse,
	PropertyGetter,
	PropertySetter,
	AddEvent,
	RemoveEvent,
	OperatorAdd,
	OperatorAnd,
	OperatorOr,
	OperatorDec,
	OperatorDiv,
	OperatorEq,
	OperatorXor,
	OperatorGt,
	OperatorGte,
	OperatorInc,
	OperatorNeq,
	OperatorLt,
	OperatorLte,
	OperatorNot,
	OperatorMod,
	OperatorMul,
	OperatorCompl,
	OperatorSub,
	OperatorNeg,
	OperatorUnaryPlus
}
